#pragma once
namespace Tetrads
{
	enum TETRADESTYPE
	{
		NILL, INIT, INPUT, OUTPUT, RETURN, BEGINBLOCK, ENDBLOCK, PLUS, MINUS, MUL, DIV, PUSH, POP, CALL, ME, M, LE, L, E, NE, IF, UNLESS, WHILE, UNTIL, FOR, ALIAS,
		PARM, DEF, MAIN, CALLPARN
	};

	
}